name: Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        ROS_DISTRO: ["noetic"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: smilerobotics/actions-ros-bloom-generate@v1
        with:
          repository_type: vcs
          vcs_setting_file: ./vcs.repos
          targets: ./cartographer ./cartographer_ros/cartographer_ros_msgs ./cartographer_ros/cartographer_ros ./cartographer_ros/cartographer_rviz
          ros_distro: ${{ matrix.ROS_DISTRO }}
          name_prefix: ${{ matrix.ROS_DISTRO }}-
          setup_dependencies_script_path: ./setup_dependencies.sh
